create table Star.FactFixture
(
    FixtureKey int not null identity(1,1) primary key,
    FixtureId int not null,
    FixtureDate datetime,
    LeagueRoundKey int not null,
    RefereeKey int not null,
    VenueKey int not null,
    HomeTeamKey int not null,
    AwayTeamKey int not null,
    Status string,
    TimeZone string,
    HalftimeHomeGoals int not null,
    HalftimeAwayGoals int not null,
    FulltimeHomeGoals int not null,
    FulltimeAwayGoals int not null,
    ExtratimeHomeGoals int,
    ExtratimeAwayGoals int,
    PenaltiesHomeGoals int,
    PenaltiesAwayGoals int,
    HomeTeamWinner boolean,
    AwayTeamWinner boolean,
    LoadDatetime timestamp default (current_timestamp()),
    UpdateDatetime timestamp default (current_timestamp()),
    foreign key (LeagueRoundKey) references Star.DimLeagueRound(LeagueRoundKey),
    foreign key (RefereeKey) references Star.DimReferee(RefereeKey),
    foreign key (VenueKey) references Star.DimVenue(VenueKey),
    foreign key (HomeTeamKey) references Star.DimTeam(TeamKey),
    foreign key (AwayTeamKey) references Star.DimTeam(TeamKey)
)