CREATE table Star.FactFixturePlayerStatistics
(
    FactFixturePlayerStatisticsKey int not null identity(1,1) primary key,
    FixtureKey int not null,
    PlayerKey int not null,
    TeamKey int not null,
    PositionKey int not null,
    CardsRed int,
    CardsYellow int,
    DribbleAttempts int,
    DribblePast int,
    DribbleSuccess int,
    DuelsTotal int,
    DuelsWon int,
    FoulsCommited int,
    FoulsDrawn int,
    Captain boolean,
    MinutesPlayed int,
    Rating numeric,
    Substitute boolean,
    GoalAssists int,
    GoalsConceded int,
    GoalSaves int,
    GoalsTotal int,
    Offsides int,
    PassAccuracy int,
    KeyPasses int,
    TotalPass int,
    PenaltiesCommited int,
    PenaltiesMissed int,
    PenaltiesSaved int,
    PenaltiesScored int,
    PenaltiesWon int,
    ShotsOnTarget int,
    ShotsTotal int,
    Blocks int,
    Interceptions int,
    TotalTackles int,
    LoadDatetime timestamp default (current_timestamp()),
    UpdateDatetime timestamp default (current_timestamp()),
    foreign key (FixtureKey) references Star.FactFixture(FixtureKey),
    foreign key (PlayerKey) references Star.DimPlayer(PlayerKey),
    foreign key (TeamKey) references Star.DimTeam(TeamKey),
    foreign key (PositionKey) references Star.DimPosition(PositionKey)
)