select
    DLR.LEAGUEROUND as MatchDay,
    SUM(FF.FULLTIMEHOMEGOALS)+SUM(FULLTIMEAWAYGOALS) AS Goals,
    SUM(FF.FULLTIMEHOMEGOALS) as HomeGoals,
    SUM(FF.FULLTIMEAWAYGOALS) as AwayGoals,
    SUM(FF.HALFTIMEHOMEGOALS) + SUM(HALFTIMEAWAYGOALS) as HalftimeGoals,
    sum(FF.HALFTIMEHOMEGOALS) as HalftimeHomeGoals,
    sum(HALFTIMEAWAYGOALS) as HalftimeAwayGoals
from star.factfixture FF
INNER JOIN star.DIMLEAGUEROUND DLR ON FF.LEAGUEROUNDKEY = DLR.LEAGUEROUNDKEY
group by DLR.LEAGUEROUND
ORDER BY RIGHT(LEAGUEROUND,2)

