create or replace table Staging.fixture_players_statistics_unflattened
(
    ExecutionInstance string,
    FixtureId bigint,
    PlayerId int,
    TeamId int,
    TeamName nvarchar(30),
    PlayerName nvarchar(30),
    CardsRed int,
    CardsYellow int,
    DribbleAttempts int,
    DribblePast int,
    DribbleSuccess int,
    DuelsTotal int,
    DuelsWon int,
    FoulsCommited int,
    FoulsDrawn int,
    Captain nvarchar(6),
    MinutesPlayed int,
    Number int,
    Position nvarchar(3),
    Rating numeric,
    Substitute nvarchar(6),
    GoalAssists int,
    GoalsConceded int,
    GoalSaves int,
    GoalsTotal int,
    Offsides int,
    PassAccuracy int,
    KeyPasses int,
    TotalPass int,
    PenaltiesCommited int,
    PenaltiesMissed int,
    PenaltiesSaved int,
    PenaltiesScored int,
    PenaltiesWon int,
    ShotsOnTarget int,
    ShotsTotal int,
    Blocks int,
    Interceptions int,
    TotalTackles int,
    LoadDatetime TIMESTAMP default(current_timestamp())
)