
CREATE or replace table Staging.fixture_flattened
(
    ExecutionInstance string,
    FixtureId BIGINT,
    FixtureDate datetime,
    Referee nvarchar(50),
    StatusShort NVARCHAR(10),
    Timezone NVARCHAR(10),
    VenueCity NVARCHAR(30),
    VenueId BIGINT,
    VenueName NVARCHAR(50),
    AwayGoals INT,
    HomeGoals INT,
    LeagueCountry NVARCHAR(20),
    LeagueName NVARCHAR(30),
    LeagueRound NVARCHAR(50),
    LeagueSeason INT,
    ExtratimeAwayGoals INT NULL,
    ExtratimeHomeGoals INT NULL,
    FulltimeAwayGoals INT NULL,
    FulltimeHomeGoals INT NULL,
    HalftimeAwayGoals INT NULL,
    HalftimeHomeGoals INT NULL,
    PenaltyHomeGoals INT NULL,
    PenaltyAwayGoals INT NULL,
    AwayTeamId INT,
    AwayTeamName NVARCHAR(20),
    AwayTeamWinner NVARCHAR(6),
    HomeTeamId INT,
    HomeTeamName NVARCHAR(20),
    HomeTeamWinner NVARCHAR(6),
    LoadDatetime timestamp default (current_timestamp()),
    UpdateDatetime timestamp default (current_timestamp())
)